version: '3.7'
services:
  web_1:
    container_name: dev_backend
    build:
      context: .
    restart: always
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/calculator
    ports:
      - "8000:8000"
    depends_on:
      - db_1
  db_1:
    container_name: dev_db
    image: postgres:12.0-alpine
    env_file: .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=calculator_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}