# Generated by Django 3.2.9 on 2021-11-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemodel',
            name='calculation_time',
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='calculation_function',
            field=models.CharField(default='s = v * t', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
