# Generated by Django 3.2.9 on 2021-11-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0004_alter_responsemodel_calculation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsemodel',
            old_name='request_id',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='rowmodel',
            old_name='request_id',
            new_name='request',
        ),
    ]
